events {}

http {
    include       /etc/nginx/mime.types;

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        # Reverse proxy: auth-service
        location /api/auth/ {
            proxy_pass http://auth-service:8080;
        }

        # Reverse proxy: core-service (include /api/uploads/**)
        location /api/ {
            proxy_pass http://core-service:8081;
        }

        # Fallback SPA: route Angular
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
