sonar.organization=antoesposito
sonar.projectKey=AntoEsposito_BugBoard26
sonar.projectName=BugBoard26

sonar.sources=backend/auth-service/src/main/java,backend/core-service/src/main/java
sonar.tests=backend/auth-service/src/test/java,backend/core-service/src/test/java
sonar.java.binaries=backend/auth-service/target/classes,backend/core-service/target/classes
sonar.java.source=25
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/target/**,frontend/**
